# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20170821_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text='Enter a book genre (e.g., Science Fiction, French Poetry etc.)', max_length=200),
        ),
    ]
